# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 16:39
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchresult",
            name="error_log",
            field=models.FileField(default=None, upload_to=b"error_logs"),
        ),
    ]
