# Generated by Django 5.2.5 on 2025-08-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0002_matchresult_error_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="docker_image",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bot",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="matchresult",
            name="error_log",
            field=models.FileField(blank=True, null=True, upload_to="error_logs"),
        ),
        migrations.AlterField(
            model_name="matchresult",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
