# Generated by Django 5.2.5 on 2025-08-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0003_bot_docker_image_alter_bot_id_alter_match_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="use_gpu",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bot",
            name="sigma",
            field=models.FloatField(default=8.333333333333334),
        ),
    ]
